// ─────────────────────────────────────────────────────────────────────────────
//  ITEM SCHEMA
//
//  Each item has:
//    name        {string}  — display name
//    slot        {string}  — which equipment slot it belongs to; must be one of
//                            SLOT_KEYS or 'bothHands' (occupies leftHand+rightHand)
//    attackType  {string|null} — combat action when used from the party panel
//                            one of: 'swipe' | 'bash' | 'shoot' | 'punch' | null
//                            (block is passive — no attackType)
//    baseDamage  {number|null} — base damage dealt per hit; null for non-weapons
//    description {string}  — flavour text shown in the item detail panel
//    value       {number}  — base gold value
//    weight      {number}  — encumbrance (future use)
// ─────────────────────────────────────────────────────────────────────────────

import { SPELLS } from './spells.js';
import POTIONS from './potions.json';

export const ACTIONS = Object.freeze({
  SWIPE: 'swipe',
  BASH: 'bash',
  SHOOT: 'shoot',
  PUNCH: 'punch',
  FIREBALL: 'fireball',
  SHIELD_BASH: 'shield-bash',
  REGENERATE: 'regenerate',
  CURE_POISON: 'cure-poison',
  HEAL: 'heal',
});

export const ITEMS = [
  ...POTIONS,

  // ── Loot / Crafting Ingredients ──────────────────────────────────────────
  {
    name: 'Life Essence',
    slot: 'loot',
    icon: '/icons/life_essence.png',
    description: 'A glowing orb of pure life energy. Prized by alchemists for crafting.',
    value: 0,
    weight: 0.1,
    sellable: false,
  },
  {
    name: 'Poison Vial',
    slot: 'loot',
    icon: '/icons/poison_vial.png',
    description: 'A small vial of concentrated poison harvested from slain creatures.',
    value: 10,
    weight: 0.2,
    sellable: true,
  },
  {
    name: 'Life Berry',
    slot: 'loot',
    icon: '/icons/life_berry.svg',
    description: 'A magical berry that pulses with natural life energy. Rare and valuable.',
    value: 10,
    weight: 0.1,
    sellable: true,
  },

  // ── Head ──────────────────────────────────────────────────────────────────
  {
    name: 'Shawl',
    slot: 'head',
    attackType: null,
    baseDamage: null,
    icon: '/icons/shawl.png',
    description: 'A worn cloth shawl pulled over the head. Offers little protection but keeps out the chill.',
    defence: 1,
    value: 2,
    weight: 0.2,
  },
  {
    name: 'Leather Cap',
    slot: 'head',
    attackType: null,
    baseDamage: null,
    icon: '/icons/leather_cap.png',
    description: 'A simple cap of boiled leather. Better than nothing.',
    defence: 2,
    value: 12,
    weight: 0.5,
  },
  {
    name: 'Iron Helm',
    slot: 'head',
    attackType: null,
    baseDamage: null,
    icon: '/icons/iron_helm.png',
    description: 'A sturdy iron helmet that covers the skull and cheeks.',
    defence: 3,
    value: 40,
    weight: 2.5,
  },

  // ── Cloak ─────────────────────────────────────────────────────────────────
  {
    name: 'Travelling Cloak',
    slot: 'cloak',
    attackType: null,
    baseDamage: null,
    description: 'A heavy wool cloak that keeps wind and rain at bay.',
    defence: 1,
    value: 8,
    weight: 1.0,
  },
  {
    name: 'Shadow Cloak',
    slot: 'cloak',
    attackType: null,
    baseDamage: null,
    description: 'A dark cloak woven with shadow-silk. Hard to see in dim light.',
    defence: 1,
    value: 80,
    weight: 0.4,
  },

  // ── Neck ──────────────────────────────────────────────────────────────────
  {
    name: 'Amulet of Warding',
    slot: 'neck',
    attackType: null,
    baseDamage: null,
    description: 'A silver amulet engraved with protective runes.',
    defence: 1,
    value: 60,
    weight: 0.1,
  },
  {
    name: 'Pendant of Focus',
    slot: 'neck',
    attackType: null,
    baseDamage: null,
    description: 'A crystal pendant that sharpens the mind and aids concentration.',
    defence: 1,
    value: 75,
    weight: 0.1,
  },

  // ── Chest ─────────────────────────────────────────────────────────────────
  {
    name: 'Padded Vest',
    slot: 'chest',
    attackType: null,
    baseDamage: null,
    icon: '/icons/padded_vest.png',
    description: 'Thick quilted padding stitched into a vest. Absorbs blows.',
    defence: 3,
    value: 15,
    weight: 2.0,
  },
  {
    name: 'Chain Shirt',
    slot: 'chest',
    attackType: null,
    baseDamage: null,
    icon: '/icons/chain_shirt.png',
    description: 'Interlocking iron rings form a flexible shirt of armour.',
    defence: 6,
    value: 90,
    weight: 5.0,
  },
  {
    name: 'Plate Cuirass',
    slot: 'chest',
    attackType: null,
    baseDamage: null,
    icon: '/icons/plate_cuirass.png',
    description: 'Heavy forged steel chest plate. Near impenetrable — if you can move in it.',
    defence: 10,
    value: 250,
    weight: 12.0,
  },

  // ── Belt ──────────────────────────────────────────────────────────────────
  {
    name: 'Leather Belt',
    slot: 'belt',
    attackType: null,
    baseDamage: null,
    icon: '/icons/leather_belt.png',
    description: 'A plain leather belt with iron buckle. Holds pouches and scabbards.',
    defence: 1,
    value: 5,
    weight: 0.3,
  },
  {
    name: 'Adventurer\'s Belt',
    slot: 'belt',
    attackType: null,
    baseDamage: null,
    icon: '/icons/adventurers_belt.png',
    description: 'A wide belt with multiple loops and pouches for quick-draw access.',
    defence: 2,
    value: 25,
    weight: 0.5,
  },

  // ── Hands (Gauntlets) ─────────────────────────────────────────────────────
  {
    name: 'Leather Gloves',
    slot: 'hands',
    attackType: null,
    baseDamage: null,
    icon: '/icons/leather_gloves.png',
    description: 'Soft leather gloves. Improve grip and protect the knuckles.',
    defence: 1,
    value: 8,
    weight: 0.3,
  },
  {
    name: 'Iron Gauntlets',
    slot: 'hands',
    attackType: null,
    baseDamage: null,
    icon: '/icons/iron_gauntlets.png',
    description: 'Articulated iron gauntlets. Protect the hands from blade and fire.',
    defence: 3,
    value: 50,
    weight: 2.0,
  },

  // ── Rings ─────────────────────────────────────────────────────────────────
  // Rings use statBonuses (a plain object mapping stat key → delta) for clean,
  // data-driven stat application.  The legacy statChange string is kept for the
  // item tooltip display only.
  {
    name: 'Ring of Vigour',
    slot: 'ring1',
    attackType: null,
    baseDamage: null,
    icon: '/icons/ring_of_vigour.png',
    description: 'A carved bone ring that pulses with vitality. Bolsters the wearer\'s constitution.',
    value: 120,
    weight: 0.05,
    statChange: '+1 Vitality',
    statBonuses: { vitality: 1 },
  },
  {
    name: 'Ring of Wisdom',
    slot: 'ring2',
    attackType: null,
    baseDamage: null,
    icon: '/icons/ring_of_wisdom.png',
    description: 'A finely crafted silver ring set with a pulsing sapphire. Sharpens the wearer\'s intelligence.',
    value: 120,
    weight: 0.05,
    statChange: '+1 Intelligence',
    statBonuses: { intelligence: 1 },
  },
  {
    name: 'Ring of Strength',
    slot: 'ring1',
    attackType: null,
    baseDamage: null,
    icon: '/icons/ring_of_strength.png',
    description: 'A heavy iron ring that radiates power. Increases physical strength.',
    value: 120,
    weight: 0.05,
    statChange: '+1 Strength',
    statBonuses: { strength: 1 },
  },
  {
    name: 'Ring of Dexterity',
    slot: 'ring1',
    attackType: null,
    baseDamage: null,
    icon: '/icons/ring_of_dexterity.png',
    description: 'A sleek golden band that feels weightless. Enhances agility and precision.',
    value: 120,
    weight: 0.05,
    statChange: '+1 Dexterity',
    statBonuses: { dexterity: 1 },
  },
  {
    name: 'Ring of Resilience',
    slot: 'ring1',
    attackType: null,
    baseDamage: null,
    icon: '/icons/ring_of_resilience.png',
    description: 'A sturdy band of dark steel. Toughens the wearer against adversity.',
    value: 120,
    weight: 0.05,
    statChange: '+1 Resilience',
    statBonuses: { resilience: 1 },
  },

  // ── Legs ──────────────────────────────────────────────────────────────────
  {
    name: 'Cloth Trousers',
    slot: 'legs',
    attackType: null,
    baseDamage: null,
    icon: '/icons/cloth_trousers.png',
    description: 'Sturdy travelling trousers. Not much protection but allow easy movement.',
    defence: 1,
    value: 4,
    weight: 0.5,
  },
  {
    name: 'Chainmail Leggings',
    slot: 'legs',
    attackType: null,
    baseDamage: null,
    icon: '/icons/chainmail_leggings.png',
    description: 'Riveted chain leggings that protect the thighs and shins.',
    defence: 4,
    value: 70,
    weight: 4.0,
  },

  // ── Feet ──────────────────────────────────────────────────────────────────
  {
    name: 'Worn Boots',
    slot: 'feet',
    attackType: null,
    baseDamage: null,
    icon: '/icons/worn_boots.png',
    description: 'A pair of well-worn leather boots. Comfortable for long marches.',
    defence: 1,
    value: 6,
    weight: 0.8,
  },
  {
    name: 'Iron-Shod Boots',
    slot: 'feet',
    attackType: null,
    baseDamage: null,
    icon: '/icons/iron_shod_boots.png',
    description: 'Reinforced leather boots with iron toe-caps. Sturdy and intimidating.',
    defence: 3,
    value: 35,
    weight: 2.0,
  },
  {
    name: 'Leather Boots',
    slot: 'feet',
    attackType: null,
    baseDamage: null,
    icon: '/leather_boots.png',
    description: 'Rugged brown leather boots, perfect for exploring dark damp corridors.',
    defence: 1,
    value: 15,
    weight: 1.0,
  },

  // ── Left Hand ─────────────────────────────────────────────────────────────
  {
    name: 'Torch',
    slot: 'rightHand',
    attackType: ACTIONS.BASH,
    baseDamage: 5,
    delay: 2,
    statWeights: { str: 1.0, dex: 0.0 }, // crude bludgeon — raw force only
    icon: '/icons/torch.png',
    description: 'A burning torch. Lights the way and can be thrust into an enemy\'s face.',
    value: 1,
    weight: 0.6,
  },
  {
    name: 'Bronze Shield',
    blockChance: 20,
    slot: 'leftHand',
    attackType: ACTIONS.SHIELD_BASH,
    baseDamage: 2,
    statWeights: { str: 1.0, dex: 0.0 }, // brute-force shove — pure strength
    icon: '/icons/bronze_shield.png',
    description: 'A round iron-banded shield. Passively deflects incoming blows.',
    defence: 2,
    value: 55,
    weight: 4.5,
  },
  {
    name: 'Wooden Shield',
    blockChance: 10,
    slot: 'leftHand',
    attackType: ACTIONS.SHIELD_BASH,
    baseDamage: 2,
    statWeights: { str: 1.0, dex: 0.0 }, // brute-force shove — pure strength
    icon: '/icons/wooden_shield.png',
    description: 'A basic shield made of reinforced wood. Offers light protection.',
    defence: 1,
    value: 20,
    weight: 2.5,
  },
  {
    name: 'Short Bow',
    slot: 'leftHand',
    attackType: ACTIONS.SHOOT,
    baseDamage: 15,
    delay: 4,
    statWeights: { str: 0.2, dex: 0.8 }, // precision aiming — mostly dexterity
    icon: '/icons/short_bow.png',
    description: 'A recurve hunting bow requiring both hands to draw. Loose to strike enemies at range.',
    value: 40,
    weight: 1.2,
  },
  {
    name: 'Crossbow',
    slot: 'leftHand',
    attackType: ACTIONS.SHOOT,
    baseDamage: 20,
    delay: 6,
    statWeights: { str: 0.5, dex: 0.5 },
    icon: '/icons/wooden-crossbow.png',
    description: 'A mechanical bow that fires powerful bolts. Slower but harder hitting than a regular bow.',
    value: 80,
    weight: 3.5,
  },
  {
    name: 'Wooden Arrows',
    slot: 'ammo',
    attackType: null,
    baseDamage: null,
    damageModifier: 1.0,
    damageType: 'normal',
    icon: '/icons/wooden_arrows.png',
    description: 'A bundle of simple wooden arrows.',
    value: 5,
    weight: 1.0,
  },
  {
    name: 'Steel Arrows',
    slot: 'ammo',
    attackType: null,
    baseDamage: null,
    damageModifier: 1.5,
    damageType: 'normal',
    icon: '/icons/steel_arrows.png',
    description: 'Sharp, steel-tipped arrows with balanced fletching. Deploys deadly force.',
    value: 25,
    weight: 1.2,
  },
  {
    name: 'Poison Arrows',
    slot: 'ammo',
    attackType: null,
    baseDamage: null,
    damageModifier: 1.0,
    damageType: 'poison',
    icon: '/icons/poison_arrows.png',
    description: 'Arrows tipped with a viscous green neurotoxin. Inflicts 1 DPS for 30 seconds.',
    value: 30,
    weight: 1.0,
  },
  {
    name: 'Dagger',
    slot: 'rightHand',
    attackType: ACTIONS.SWIPE,
    baseDamage: 5,
    delay: 2,
    statWeights: { str: 0.2, dex: 0.8 }, // pure finesse — speed and precision
    icon: '/icons/dagger.png',
    description: 'A short, double-edged blade. Quick and easy to slip past armour.',
    value: 20,
    weight: 0.4,
  },
  {
    name: 'Main Gauche',
    slot: 'leftHand',
    attackType: ACTIONS.SWIPE,
    baseDamage: 5,
    delay: 2,
    statWeights: { str: 0.2, dex: 0.8 },
    icon: '/icons/dagger.png',
    description: 'A parrying dagger designed for the off-hand. Enables dual-wielding.',
    value: 30,
    weight: 0.5,
  },

  // ── Right Hand ────────────────────────────────────────────────────────────
  {
    name: 'Sword',
    slot: 'rightHand',
    attackType: ACTIONS.SWIPE,
    baseDamage: 10,
    delay: 2,
    statWeights: { str: 0.5, dex: 0.5 }, // versatile balanced blade
    icon: '/icons/sword.png',
    description: 'A straight iron sword. The classic weapon of choice for adventurers.',
    value: 65,
    weight: 1.8,
  },
  {
    name: 'Oak Staff',
    slot: 'enable-spell',
    attackType: ACTIONS.BASH,
    baseDamage: 5,
    delay: 4,
    statWeights: { str: 0.8, dex: 0.2 }, // bludgeoning reach weapon — mostly strength
    icon: '/icons/oak_staff.png',
    description: 'A gnarled wooden staff. Requires one hand, but enables a spell in the offhand.',
    value: 18,
    weight: 1.5,
  },
  {
    name: 'Spellbook',
    slot: 'spell',
    attackType: null,
    baseDamage: null,
    delay: 4,
    icon: '/icons/spellbook.png',
    description: 'An ancient tome. Once equipped, Right-Click it in the paperdoll to select your active spell.',
    value: 120,
    weight: 1.0,
    isSpellBook: true // identifies it for the UI
  },
  {
    name: 'Axe',
    slot: 'rightHand',
    attackType: ACTIONS.SWIPE,
    baseDamage: 10,
    delay: 2,
    statWeights: { str: 0.8, dex: 0.2 }, // heavy chopping — mostly strength
    icon: '/icons/axe.png',
    description: 'A heavy war axe. Slower than a sword but hits with devastating force.',
    value: 50,
    weight: 2.8,
  },
  {
    name: 'Mace',
    slot: 'rightHand',
    attackType: ACTIONS.BASH,
    baseDamage: 15,
    delay: 2,
    statWeights: { str: 1.0, dex: 0.0 }, // pure brute force — strength only
    icon: '/icons/mace.png',
    description: 'An iron mace with a flanged head. Excellent against armoured foes.',
    value: 45,
    weight: 2.2,
  },

  // ── Both Hands ────────────────────────────────────────────────────────────

  {
    name: 'Greatsword',
    slot: 'bothHands',
    attackType: ACTIONS.SWIPE,
    baseDamage: 30,
    delay: 4,
    statWeights: { str: 0.7, dex: 0.3 }, // power + technique to control the massive blade
    icon: '/icons/greatsword.png',
    description: 'A massive two-handed blade that cleaves through enemies in a single arc.',
    value: 150,
    weight: 5.5,
  },
  {
    name: 'Greataxe',
    slot: 'bothHands',
    attackType: ACTIONS.SWIPE,
    baseDamage: 20,
    delay: 4,
    statWeights: { str: 1.0, dex: 0.0 }, // pure cleaving force — no finesse needed
    icon: '/icons/greataxe.png',
    description: 'A massive two-handed axe that cleaves through enemies in a single arc.',
    value: 150,
    weight: 5.5,
  },
  {
    name: 'War Hammer',
    slot: 'bothHands',
    attackType: ACTIONS.BASH,
    baseDamage: 25,
    delay: 4,
    statWeights: { str: 1.0, dex: 0.0 }, // crushing weight — pure strength
    icon: '/icons/war_hammer.png',
    description: 'A two-handed war hammer. Slow to swing but crushes stone and bone alike.',
    value: 130,
    weight: 7.0,
  },
  {
    name: 'Longbow',
    slot: 'leftHand',
    attackType: ACTIONS.SHOOT,
    baseDamage: 20,
    delay: 4,
    statWeights: { str: 0.3, dex: 0.7 }, // heavier draw weight needs some strength, mostly dex
    icon: '/icons/longbow.png',
    description: 'A tall yew longbow requiring both hands. Tremendous range and power.',
    value: 75,
    weight: 1.8,
  },
  {
    name: 'Battle Cry',
    slot: 'skill',
    type: 'debuff',
    icon: '/icons/skill_generic.svg',
    description: 'A terrifying shout that demoralizes enemies.',
    value: 0,
    weight: 0,
  },
  {
    name: 'Focus',
    slot: 'skill',
    type: 'buff',
    icon: '/icons/skill_generic.svg',
    description: 'Concentrate for increased critical hit chance.',
    value: 0,
    weight: 0,
  },
  {
    name: 'Holy Shield',
    slot: 'skill',
    type: 'buff',
    blockChance: 20,
    attackType: ACTIONS.BASH,
    baseDamage: 2,
    statWeights: { str: 1.0, dex: 0.0 }, // divine force — pure strength
    icon: '/icons/skill_generic.svg',
    description: 'Divine protection against physical attacks.',
    value: 0,
    weight: 0,
  },
  {
    name: 'Sunder Armor',
    slot: 'skill',
    type: 'debuff',
    icon: '/skills/sunder-armor.png',
    description: 'Crushes the targeted monster, halving its defence stats for 30s.',
    value: 0,
    weight: 0,
  },
  {
    name: 'Whirlwind',
    slot: 'skill',
    type: 'buff',
    icon: '/skills/whirlwind.png',
    description: 'Becomes a blur of motion, doubling attack speed and preventing stamina drain for 30s.',
    value: 0,
    weight: 0,
  },
  {
    name: 'True Shot',
    slot: 'skill',
    type: 'buff',
    icon: '/skills/true-shot.png',
    description: 'Becomes hyper-focused, ensuring every ranged attack finds its mark for 20 seconds.',
    value: 0,
    weight: 0,
  },
  {
    name: 'Miners Light',
    slot: 'skill',
    type: 'buff',
    icon: '/skills/arcane-lantern.png',
    description: 'Ignites a specialized lantern, illuminating the dungeon brightly for 60 seconds.',
    value: 0,
    weight: 0,
  },
  {
    name: 'Rage',
    slot: 'skill',
    type: 'buff',
    icon: '/icons/skill_generic.svg',
    description: 'Unleash inner fury for increased damage.',
    value: 0,
    weight: 0,
  },
  {
    name: 'Heal Spellbook',
    type: 'spellbook',
    spellName: 'Heal',
    requiredInt: 8,
    icon: '/icons/heal.png',
    description: 'A vellum scroll containing restorative prayers. Requires 8 Intelligence to decypher.',
    value: 150,
    weight: 0.5,
  },
  {
    name: 'Regeneration Spellbook',
    type: 'spellbook',
    spellName: 'Regeneration',
    requiredInt: 12,
    icon: '/icons/regeneration.png',
    description: 'A thick book smelling of damp earth and moss. Requires 12 Intelligence to decypher.',
    value: 250,
    weight: 1.2,
  },
  {
    name: 'Cure Poison Spellbook',
    type: 'spellbook',
    spellName: 'Cure Poison',
    requiredInt: 6,
    icon: '/icons/cure-poison.png',
    description: 'A small pamphlet detailed with botanical sketches. Requires 6 Intelligence to decypher.',
    value: 100,
    weight: 0.3,
  },

  // ── Spell Cabinet Scrolls (starter room) ──────────────────────────────────
  // All four require 10 Intelligence to learn. Consumed on use.
  {
    name: 'Scroll of Fireball',
    type: 'spellbook',
    spellName: 'Fireball',
    requiredInt: 10,
    icon: '/icons/scroll_fireball.png',
    description: 'Ancient parchment inscribed with blazing runes. Study it to learn Fireball. Requires 10 Intelligence.',
    value: 200,
    weight: 0.2,
  },
  {
    name: 'Scroll of Heal',
    type: 'spellbook',
    spellName: 'Heal',
    requiredInt: 10,
    icon: '/icons/scroll_heal.png',
    description: 'A roll of white vellum filled with restorative prayers. Study it to learn Heal. Requires 10 Intelligence.',
    value: 180,
    weight: 0.2,
  },
  {
    name: 'Scroll of Regeneration',
    type: 'spellbook',
    spellName: 'Regeneration',
    requiredInt: 10,
    icon: '/icons/scroll_regeneration.png',
    description: 'A scroll smelling of damp earth and fresh moss. Study it to learn Regeneration. Requires 10 Intelligence.',
    value: 220,
    weight: 0.2,
  },
  {
    name: 'Scroll of Cure Poison',
    type: 'spellbook',
    spellName: 'Cure Poison',
    requiredInt: 10,
    icon: '/icons/scroll_cure_poison.png',
    description: 'A scroll bearing botanical sketches and purifying incantations. Study it to learn Cure Poison. Requires 10 Intelligence.',
    value: 160,
    weight: 0.2,
  },
];


// ─────────────────────────────────────────────────────────────────────────────
//  LOOKUP HELPER
// ─────────────────────────────────────────────────────────────────────────────

export function getItemDef(name) {
  return ITEMS.find((item) => item.name === name)
    ?? SPELLS.find((spell) => spell.name === name)
    ?? null;
}
