import { inst } from '../../monster-factory.js';
import { MONSTER_DEFS as D } from '../../monster-defs.js';
import { asset } from '../../assets.js';

// ─────────────────────────────────────────────────────────────────────────────
//  LEVEL 1 – The Western Dungeon
// ─────────────────────────────────────────────────────────────────────────────

export const level1Monsters = [
  // North dead-end passage (behind the portcullis — opens when the wall button is pressed)
  inst(D.treekin, 0, 3, 7,
    asset('/monsters/treekin-animation/Meshy_AI_Animation_Walking_withSkin.glb'),
    asset('/monsters/treekin-animation/Meshy_AI_Animation_mage_soell_cast_withSkin.glb'),
    asset('/monsters/treekin-animation/treeKin-attack.mp3'), 0.45, 0, 0, 1, null,
    asset('/monsters/treekin-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/treekin-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb')),

  // Upper maze
  inst(D.goblin, 1, 9, 6,
    asset('/monsters/goblin-animation/goblin-alert.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Double_Combo_Attack_withSkin.glb'),
    asset('/monsters/goblin-animation/goblin-attack.wav'), 0.45, 0, 0, 1, null,
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Walking_withSkin.glb')),

  // Southern section
  inst(D.night_goblin, 2, 15, 5,
    asset('/monsters/night-goblin/idle.glb'),
    asset('/monsters/night-goblin/single-attack.glb'),
    asset('/monsters/night-goblin/goblin-attack.wav'), 0.45, 0, 0, 1, null,
    asset('/monsters/night-goblin/dead.glb'),
    null,
    asset('/monsters/night-goblin/walking.glb'),
    null,
    asset('/monsters/night-goblin/cobat-idle.glb')),

  // Lower maze — zombie lurks in the far lower-right section, well past the row-14 barrier
  inst(D.mushroom, 3, 17, 12,
    asset('/monsters/mushroom/idle.glb'),
    asset('/monsters/mushroom/attack.glb'),
    null, 0.45, 0, 0, 1, null,
    asset('/monsters/mushroom/dead.glb'),
    null,
    asset('/monsters/mushroom/walk.glb'),
    null,
    asset('/monsters/mushroom/combat-idle.glb')),

  // Lower maze
  inst(D.mushroom, 4, 17, 11,
    asset('/monsters/mushroom/idle.glb'),
    asset('/monsters/mushroom/attack.glb'),
    null, 0.45, 0, 0, 1, null,
    asset('/monsters/mushroom/dead.glb'),
    null,
    asset('/monsters/mushroom/walk.glb'),
    null,
    asset('/monsters/mushroom/combat-idle.glb')),

  // Deeper south passage
  inst(D.orc_warrior, 7, 19, 8,
    asset('/monsters/orc-warrior/idle-normal.glb'),
    asset('/monsters/orc-warrior/attack1.glb'),
    asset('/monsters/orc-warrior/attack1.mp3'),
    0.5, 0, 0, 1, null,
    asset('/monsters/orc-warrior/getting-killed.glb'),
    asset('/monsters/orc-warrior/getting-hit.glb'),
    asset('/monsters/orc-warrior/walking.glb'),
    null,
    asset('/monsters/orc-warrior/idle-combat.glb')),

  // Bottom long corridor
  inst(D.iceman, 5, 21, 5,
    asset('/monsters/iceMan-animation/Meshy_AI_Animation_Walking_withSkin.glb'),
    asset('/monsters/iceMan-animation/Meshy_AI_Animation_Double_Combo_Attack_withSkin.glb'),
    asset('/monsters/iceMan-animation/iceman-attack.mp3'), 0.6, 0, 0, 1, null,
    asset('/monsters/iceMan-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/iceMan-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb')),

  // Ogre in the north-west room — on patrol
  inst(D.ogre, 21, 2, 2,
    asset('/monsters/ogre/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/ogre/Meshy_AI_Animation_Punch_Combo_withSkin.glb'),
    asset('/monsters/ogre/ogre.mp3'), 0.7, 0, 0, 1,
    { bounds: { minRow: 1, maxRow: 5, minCol: 1, maxCol: 5 }, speed: 0.5, waitTime: 2.0 },
    asset('/monsters/ogre/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/ogre/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/ogre/Meshy_AI_Animation_Walking_withSkin.glb'),
    asset('/monsters/ogre/Meshy_AI_Animation_Idle_03_withSkin.glb'),
    asset('/monsters/ogre/combat-idle.glb')),

  // Goblin guard in the vertical passage leading to the Northwest room
  inst(D.goblin, 23, 8, 1,
    asset('/monsters/goblin-animation/goblin-alert.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Double_Combo_Attack_withSkin.glb'),
    asset('/monsters/goblin-animation/goblin-attack.wav'), 0.45, 0, 0, 1, null,
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Walking_withSkin.glb')),

  inst(D.treekin, 61, 7, 5,
    asset('/monsters/treekin-animation/Meshy_AI_Animation_Walking_withSkin.glb'),
    asset('/monsters/treekin-animation/Meshy_AI_Animation_mage_soell_cast_withSkin.glb'),
    asset('/monsters/treekin-animation/treeKin-attack.mp3'), 0.45, 0, 0, 1, null,
    asset('/monsters/treekin-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/treekin-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb')),

  inst(D.mushroom, 62, 15, 10,
    asset('/monsters/mushroom/idle.glb'),
    asset('/monsters/mushroom/attack.glb'),
    null, 0.45, 0, 0, 1, null,
    asset('/monsters/mushroom/dead.glb'),
    null,
    asset('/monsters/mushroom/walk.glb'),
    null,
    asset('/monsters/mushroom/combat-idle.glb')),

  // Additional Goblins spread through Level 1 corridors (avoiding big rooms)
  inst(D.goblin, 25, 13, 1,
    asset('/monsters/goblin-animation/goblin-alert.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Double_Combo_Attack_withSkin.glb'),
    asset('/monsters/goblin-animation/goblin-attack.wav'), 0.45, 0, 0, 1, null,
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Walking_withSkin.glb')),

  inst(D.goblin, 26, 18, 3,
    asset('/monsters/goblin-animation/goblin-alert.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Double_Combo_Attack_withSkin.glb'),
    asset('/monsters/goblin-animation/goblin-attack.wav'), 0.45, 0, 0, 1, null,
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Walking_withSkin.glb')),

  inst(D.goblin, 27, 19, 4,
    asset('/monsters/goblin-animation/goblin-alert.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Double_Combo_Attack_withSkin.glb'),
    asset('/monsters/goblin-animation/goblin-attack.wav'), 0.45, 0, 0, 1, null,
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Walking_withSkin.glb')),

  // Mummies in the secret room (Rows 1-4, Cols 17-20)
  inst(D.mummy, 101, 2, 18,
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Double_Combo_Attack_withSkin.glb'),
    asset('/monsters/mummy-annimation/mummy-attack.mp3'), 0.45, 0, 0, 1, null,
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Dead_withSkin.glb'),
    null,
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Walking_withSkin.glb')),

  inst(D.mummy, 102, 3, 18,
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Double_Combo_Attack_withSkin.glb'),
    asset('/monsters/mummy-annimation/mummy-attack.mp3'), 0.45, 0, 0, 1, null,
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Dead_withSkin.glb'),
    null,
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Walking_withSkin.glb')),

  inst(D.mummy, 103, 4, 18,
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Double_Combo_Attack_withSkin.glb'),
    asset('/monsters/mummy-annimation/mummy-attack.mp3'), 0.45, 0, 0, 1, null,
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Dead_withSkin.glb'),
    null,
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Walking_withSkin.glb')),

  // Night Goblins in the secret room north of the zombie room (Rows 11-13, Cols 15-19)
  inst(D.night_goblin, 108, 12, 16,
    asset('/monsters/night-goblin/idle.glb'),
    asset('/monsters/night-goblin/single-attack.glb'),
    asset('/monsters/night-goblin/goblin-attack.wav'), 0.45, 0, 0, 1, null,
    asset('/monsters/night-goblin/dead.glb'),
    null,
    asset('/monsters/night-goblin/walking.glb'),
    null,
    asset('/monsters/night-goblin/cobat-idle.glb')),

  inst(D.night_goblin, 109, 12, 18,
    asset('/monsters/night-goblin/idle.glb'),
    asset('/monsters/night-goblin/single-attack.glb'),
    asset('/monsters/night-goblin/goblin-attack.wav'), 0.45, 0, 0, 1, null,
    asset('/monsters/night-goblin/dead.glb'),
    null,
    asset('/monsters/night-goblin/walking.glb'),
    null,
    asset('/monsters/night-goblin/cobat-idle.glb')),

  // Zombies in the hidden room (Rows 17-20, Cols 16-19)
  inst(D.zombie, 105, 18, 17,
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Idle_3_withSkin.glb'),
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Double_Combo_Attack_withSkin.glb'),
    asset('/monsters/zombie-animation/zombie-attack.mp3'), 0.45, 0, 0, 1,
    { bounds: { minRow: 17, maxRow: 20, minCol: 16, maxCol: 19 }, speed: 0.4, waitTime: 2.0 },
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Walking_withSkin.glb'),
    null,
    asset('/monsters/zombie-animation/zombie-combat-idle.glb')),

  inst(D.zombie, 106, 18, 18,
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Idle_3_withSkin.glb'),
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Double_Combo_Attack_withSkin.glb'),
    asset('/monsters/zombie-animation/zombie-attack.mp3'), 0.45, 0, 0, 1,
    { bounds: { minRow: 17, maxRow: 20, minCol: 16, maxCol: 19 }, speed: 0.4, waitTime: 2.0 },
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Walking_withSkin.glb'),
    null,
    asset('/monsters/zombie-animation/zombie-combat-idle.glb')),

  inst(D.zombie, 107, 19, 18,
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Idle_3_withSkin.glb'),
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Double_Combo_Attack_withSkin.glb'),
    asset('/monsters/zombie-animation/zombie-attack.mp3'), 0.45, 0, 0, 1,
    { bounds: { minRow: 17, maxRow: 20, minCol: 16, maxCol: 19 }, speed: 0.4, waitTime: 2.0 },
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/zombie-animation/Meshy_AI_Animation_Walking_withSkin.glb'),
    null,
    asset('/monsters/zombie-animation/zombie-combat-idle.glb')),

  // Mushrooms guarding the Scroll of Resist Fear cabinet (rows 11-12, col 11)
  inst(D.mushroom, 72, 11, 11,
    asset('/monsters/mushroom/idle.glb'),
    asset('/monsters/mushroom/attack.glb'),
    null, 0.45, 0, 0, 1, null,
    asset('/monsters/mushroom/dead.glb'),
    null,
    asset('/monsters/mushroom/walk.glb'),
    null,
    asset('/monsters/mushroom/combat-idle.glb')),

  inst(D.mushroom, 73, 11, 13,
    asset('/monsters/mushroom/idle.glb'),
    asset('/monsters/mushroom/attack.glb'),
    null, 0.45, 0, 0, 1, null,
    asset('/monsters/mushroom/dead.glb'),
    null,
    asset('/monsters/mushroom/walk.glb'),
    null,
    asset('/monsters/mushroom/combat-idle.glb')),

  // Mummy in the Level 1 pit arrival room (24, 1)
  inst(D.mummy, 104, 24, 1,
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Double_Combo_Attack_withSkin.glb'),
    asset('/monsters/mummy-annimation/mummy-attack.mp3'), 0.45, 0, 0, 1, null,
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Dead_withSkin.glb'),
    null,
    asset('/monsters/mummy-annimation/Meshy_AI_Animation_Walking_withSkin.glb')),
];
