import { inst } from '../../monster-factory.js';
import { MONSTER_DEFS as D } from '../../monster-defs.js';
import { asset } from '../../assets.js';

// ─────────────────────────────────────────────────────────────────────────────
//  LEVEL 3 – The Abyssal Crypts
// ─────────────────────────────────────────────────────────────────────────────

export const level3Monsters = [
  // ── Central Chamber ─────────────────────────────────────────────────────
  // Minotaur boss patrols the central room
  inst(D.minotaur, 300, 11, 8,
    asset('/monsters/minotaur/Meshy_AI_Animation_Idle_03_withSkin.glb'),
    asset('/monsters/minotaur/Meshy_AI_Animation_Attack_withSkin.glb'),
    asset('/monsters/minotaur/minator-attack.mp3'), 0.8, 0, 0, 3,
    { bounds: { minRow: 9, maxRow: 13, minCol: 7, maxCol: 10 }, speed: 0.6, waitTime: 1.5 },
    asset('/monsters/minotaur/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/minotaur/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/minotaur/Meshy_AI_Animation_Walking_withSkin.glb'),
    asset('/monsters/minotaur/Meshy_AI_Animation_Alert_withSkin.glb')),

  // ── North-West Room (4 Skeletons, 1 Demon) ──────────────────────────────
  inst(D.skeletonWarrior, 311, 2, 2,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 312, 2, 4,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 313, 4, 2,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 314, 4, 4,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.demon, 315, 3, 3,
    asset('/monsters/demon/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/demon/Meshy_AI_Animation_Charged_Slash_withSkin.glb'),
    asset('/monsters/demon/demon-hit.mp3'), 0.65, 0, 0, 3, null,
    asset('/monsters/demon/Meshy_AI_Animation_Fall_Dead_from_Abdominal_Injury_withSkin.glb'),
    asset('/monsters/demon/Meshy_AI_Animation_Slap_Reaction_withSkin.glb'),
    asset('/monsters/demon/Meshy_AI_Animation_Walking_withSkin.glb')),

  // ── North-East Room (4 Skeletons, 1 Aqua Man) ───────────────────────────
  inst(D.skeletonWarrior, 321, 2, 17,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 322, 2, 19,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 323, 4, 17,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 324, 4, 19,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.aqua_man, 325, 3, 18,
    asset('/monsters/aqua-man/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/aqua-man/Meshy_AI_Animation_Punch_Combo_withSkin.glb'),
    asset('/monsters/aqua-man/aqua-attack.mp3'), 0.60, 0, 0, 3, null,
    asset('/monsters/aqua-man/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/aqua-man/Meshy_AI_Animation_Face_Punch_Reaction_1_withSkin.glb'),
    asset('/monsters/aqua-man/Meshy_AI_Animation_Walking_withSkin.glb')),

  // ── South-West Room (4 Skeletons, 1 Aqua Man) ───────────────────────────
  inst(D.skeletonWarrior, 331, 18, 2,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 332, 18, 4,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 333, 20, 2,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 334, 20, 4,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.aqua_man, 335, 19, 3,
    asset('/monsters/aqua-man/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/aqua-man/Meshy_AI_Animation_Punch_Combo_withSkin.glb'),
    asset('/monsters/aqua-man/aqua-attack.mp3'), 0.60, 0, 0, 3, null,
    asset('/monsters/aqua-man/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/aqua-man/Meshy_AI_Animation_Face_Punch_Reaction_1_withSkin.glb'),
    asset('/monsters/aqua-man/Meshy_AI_Animation_Walking_withSkin.glb')),

  // ── South-East Room (4 Skeletons, 1 Demon) ──────────────────────────────
  inst(D.skeletonWarrior, 341, 18, 17,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 342, 18, 19,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 343, 20, 17,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 344, 20, 19,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.demon, 345, 19, 18,
    asset('/monsters/demon/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/demon/Meshy_AI_Animation_Charged_Slash_withSkin.glb'),
    asset('/monsters/demon/demon-hit.mp3'), 0.65, 0, 0, 3, null,
    asset('/monsters/demon/Meshy_AI_Animation_Fall_Dead_from_Abdominal_Injury_withSkin.glb'),
    asset('/monsters/demon/Meshy_AI_Animation_Slap_Reaction_withSkin.glb'),
    asset('/monsters/demon/Meshy_AI_Animation_Walking_withSkin.glb')),

  // ── Elemental Shrine Guard (Goblin by Red Crystal shrine) ──────────────
  inst(D.goblin, 360, 11, 18,
    asset('/monsters/goblin-animation/goblin-alert.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Double_Combo_Attack_withSkin.glb'),
    asset('/monsters/goblin-animation/goblin-attack.wav'), 0.45, 0, 0, 3, null,
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/goblin-animation/Meshy_AI_Animation_Walking_withSkin.glb')),

  // ── Corridor Patrols (2 Crocodile Warriors) ─────────────────────────────
  // West vertical corridor, mid-section
  inst(D.crocodile_warrior, 350, 10, 3,
    asset('/monsters/crocodile-warrior/idle.glb'),
    asset('/monsters/crocodile-warrior/double-attack.glb'),
    asset('/monsters/crocodile-warrior/attack.mp3'), 0.65, 0, 0, 3, null,
    asset('/monsters/crocodile-warrior/dead.glb'),
    asset('/monsters/crocodile-warrior/getting-hit.glb'),
    asset('/monsters/crocodile-warrior/walking.glb'), null,
    asset('/monsters/crocodile-warrior/combat-idle.glb')),
  // East vertical corridor, northern section
  inst(D.crocodile_warrior, 351, 6, 18,
    asset('/monsters/crocodile-warrior/idle.glb'),
    asset('/monsters/crocodile-warrior/double-attack.glb'),
    asset('/monsters/crocodile-warrior/attack.mp3'), 0.65, 0, 0, 3, null,
    asset('/monsters/crocodile-warrior/dead.glb'),
    asset('/monsters/crocodile-warrior/getting-hit.glb'),
    asset('/monsters/crocodile-warrior/walking.glb'), null,
    asset('/monsters/crocodile-warrior/combat-idle.glb')),
];
