import { inst } from '../../monster-factory.js';
import { MONSTER_DEFS as D } from '../../monster-defs.js';
import { asset } from '../../assets.js';

// ─────────────────────────────────────────────────────────────────────────────
//  LEVEL 3 – The Abyssal Crypts
// ─────────────────────────────────────────────────────────────────────────────

// Two swamp monsters share the room but patrol opposite halves, with a neutral
// gap (cols 8-11) between their zones so the party can pull and fight one at a
// time. An aggroed monster chases freely (ignores these bounds), so kiting one
// across the gap — or fighting near the middle — risks waking the other.
const SWAMP_PATROL_WEST = { bounds: { minRow: 1, maxRow: 5, minCol: 1, maxCol: 7 }, speed: 0.35, waitTime: 2.5 };
const SWAMP_PATROL_EAST = { bounds: { minRow: 1, maxRow: 5, minCol: 12, maxCol: 18 }, speed: 0.35, waitTime: 2.5 };

function _makeSwampMonster(id, row, col, patrol) {
  const m = inst(D.swamp_monster, id, row, col,
    asset('/monsters/swamp-monster/walking.glb'),
    asset('/monsters/swamp-monster/attack.glb'),
    asset('/monsters/swamp-monster/attack.mp3'),
    0.5, 0, 0, 3,
    patrol,
    asset('/monsters/swamp-monster/dead.glb'),
    null,
    asset('/monsters/swamp-monster/walking.glb'),
    null,
    asset('/monsters/swamp-monster/combat-idle.glb'),
  );
  m.tauntSound = asset('/monsters/swamp-monster/swamp-monster.mp3');
  m.tauntSoundRadius = 3;
  return m;
}

export const level3Monsters = [
  // ── Central Chamber ─────────────────────────────────────────────────────
  // Minotaur boss patrols the central room
  inst(D.minotaur, 300, 17, 8,
    asset('/monsters/minotaur/Meshy_AI_Animation_Idle_03_withSkin.glb'),
    asset('/monsters/minotaur/Meshy_AI_Animation_Attack_withSkin.glb'),
    asset('/monsters/minotaur/minator-attack.mp3'), 0.8, 0, 0, 3,
    { bounds: { minRow: 15, maxRow: 19, minCol: 7, maxCol: 10 }, speed: 0.6, waitTime: 1.5 },
    asset('/monsters/minotaur/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/minotaur/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/minotaur/Meshy_AI_Animation_Walking_withSkin.glb'),
    asset('/monsters/minotaur/Meshy_AI_Animation_Alert_withSkin.glb')),

  // ── Swamp Room (2 Swamp Monsters — west & east, kept far apart) ──────────
  // The party enters from the south passage (col 3) into the west monster's
  // zone; the east monster guards the far side near the cauldron alcove. Each
  // can be isolated, but pulling both at once is a serious fight.
  _makeSwampMonster(361, 3, 3, SWAMP_PATROL_WEST),
  _makeSwampMonster(362, 3, 16, SWAMP_PATROL_EAST),

  // ── North-West Room (4 Skeletons, 1 Demon) ──────────────────────────────
  inst(D.skeletonWarrior, 311, 8, 2,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 312, 8, 4,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 313, 10, 2,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 314, 10, 4,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.demon, 315, 9, 3,
    asset('/monsters/demon/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/demon/Meshy_AI_Animation_Charged_Slash_withSkin.glb'),
    asset('/monsters/demon/demon-hit.mp3'), 0.65, 0, 0, 3, null,
    asset('/monsters/demon/Meshy_AI_Animation_Fall_Dead_from_Abdominal_Injury_withSkin.glb'),
    asset('/monsters/demon/Meshy_AI_Animation_Slap_Reaction_withSkin.glb'),
    asset('/monsters/demon/Meshy_AI_Animation_Walking_withSkin.glb')),

  // ── North-East Room (4 Skeletons, 1 Aqua Man) ───────────────────────────
  inst(D.skeletonWarrior, 321, 8, 17,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 322, 8, 19,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 323, 10, 17,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 324, 10, 19,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.aqua_man, 325, 9, 18,
    asset('/monsters/aqua-man/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/aqua-man/Meshy_AI_Animation_Punch_Combo_withSkin.glb'),
    asset('/monsters/aqua-man/aqua-attack.mp3'), 0.60, 0, 0, 3, null,
    asset('/monsters/aqua-man/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/aqua-man/Meshy_AI_Animation_Face_Punch_Reaction_1_withSkin.glb'),
    asset('/monsters/aqua-man/Meshy_AI_Animation_Walking_withSkin.glb')),

  // ── South-West Room (4 Skeletons, 1 Aqua Man) ───────────────────────────
  inst(D.skeletonWarrior, 331, 24, 2,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 332, 24, 4,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 333, 26, 2,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 334, 26, 4,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.aqua_man, 335, 25, 3,
    asset('/monsters/aqua-man/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/aqua-man/Meshy_AI_Animation_Punch_Combo_withSkin.glb'),
    asset('/monsters/aqua-man/aqua-attack.mp3'), 0.60, 0, 0, 3, null,
    asset('/monsters/aqua-man/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/aqua-man/Meshy_AI_Animation_Face_Punch_Reaction_1_withSkin.glb'),
    asset('/monsters/aqua-man/Meshy_AI_Animation_Walking_withSkin.glb')),

  // ── South-East Room (4 Skeletons, 1 Demon) ──────────────────────────────
  inst(D.skeletonWarrior, 341, 24, 17,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 342, 24, 19,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 343, 26, 17,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.skeletonWarrior, 344, 26, 19,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Triple_Combo_Attack_withSkin.glb'),
    asset('/monsters/skeleton-animation/attack - Copy.mp3'), 0.5, 0, 0, 3, null,
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Dead_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Hit_Reaction_1_withSkin.glb'),
    asset('/monsters/skeleton-animation/Meshy_AI_Animation_Walking_withSkin.glb')),
  inst(D.demon, 345, 25, 18,
    asset('/monsters/demon/Meshy_AI_Animation_Idle_withSkin.glb'),
    asset('/monsters/demon/Meshy_AI_Animation_Charged_Slash_withSkin.glb'),
    asset('/monsters/demon/demon-hit.mp3'), 0.65, 0, 0, 3, null,
    asset('/monsters/demon/Meshy_AI_Animation_Fall_Dead_from_Abdominal_Injury_withSkin.glb'),
    asset('/monsters/demon/Meshy_AI_Animation_Slap_Reaction_withSkin.glb'),
    asset('/monsters/demon/Meshy_AI_Animation_Walking_withSkin.glb')),


  // ── Secret Room (2 Crocodile Warriors) ──────────────────────────────────
  inst(D.crocodile_warrior, 352, 11, 14,
    asset('/monsters/crocodile-warrior/idle.glb'),
    asset('/monsters/crocodile-warrior/double-attack.glb'),
    asset('/monsters/crocodile-warrior/attack.mp3'), 0.65, 0, 0, 3, null,
    asset('/monsters/crocodile-warrior/dead.glb'),
    asset('/monsters/crocodile-warrior/getting-hit.glb'),
    asset('/monsters/crocodile-warrior/walking.glb'), null,
    asset('/monsters/crocodile-warrior/combat-idle.glb')),
  inst(D.crocodile_warrior, 353, 13, 14,
    asset('/monsters/crocodile-warrior/idle.glb'),
    asset('/monsters/crocodile-warrior/double-attack.glb'),
    asset('/monsters/crocodile-warrior/attack.mp3'), 0.65, 0, 0, 3, null,
    asset('/monsters/crocodile-warrior/dead.glb'),
    asset('/monsters/crocodile-warrior/getting-hit.glb'),
    asset('/monsters/crocodile-warrior/walking.glb'), null,
    asset('/monsters/crocodile-warrior/combat-idle.glb')),
];
